name: morty_api
description: Simple images list

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2

  # Architecture
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  provider: ^6.0.4
  injectable: ^2.1.2
  get_it: ^7.6.0

  # Network
  json_annotation: ^4.7.0
  dio: ^4.0.6
  retrofit: ^3.3.1

  # Utils
  fimber: ^0.6.6
  #analyzer: ^5.2.0

dependency_overrides:
  analyzer: ">=5.2.0 <=5.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  retrofit_generator: 4.2.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  dart_code_metrics: ^5.4.0
  injectable_generator: ^2.1.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
